---
# Â©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Get Vertica node name
  command: /opt/vertica/bin/vsql -U dbadmin -w '{{ vertica_dbadmin_password }}' -t -A -c "select NODE_NAME from CURRENT_SESSION;"
  sudo_user: dbadmin
  environment: "{{vertica_env}}"
  register: vertica_node

- name: Set vertica_node name
  set_fact: vertica_node_name={{vertica_node.stdout}}

- name: Place logrotate conf for vertica
  template: src=vertica_logrotate.j2 dest=/opt/vertica/config/logrotate/{{ vertica_database_name }} owner=root group=root mode=644
