---
# Â©Copyright 2015 Hewlett-Packard Development Company, L.P.

- name: Install Vertica dependencies (apt)
  apt: name="{{item}}" state=present
  with_items: vertica_dependencies
  when: not skip_install and ansible_os_family == 'Debian'

- name: Install Vertica dependencies (yum)
  yum: name="{{item}}" state=present
  with_items: vertica_dependencies
  when: not skip_install and ansible_os_family == 'RedHat'

- name: Setup User limits for the db
  template: dest=/etc/security/limits.d/vertica.conf owner=root group=root mode=644 src=vertica_limits.conf.j2

- name: Apply security limits to su sessions, admintools needs this as it uses su
  lineinfile: dest=/etc/pam.d/su regexp="^#\ssession    required   pam_limits.so" line="session    required   pam_limits.so" backrefs=yes

- name: Set the LANG variable
  copy:
    dest: /etc/profile.d/vertica_node.sh
    content: "export LANG='en_US.UTF-8'\nexport LC_ALL='en_US.UTF-8'\n"
    owner: root
    group: root
    mode: 644

- name: Create en_US.UTF-8 locale
  shell: localedef -i en_US -c -f UTF-8 en_US.UTF-8
